include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    # generated Dart
    - "**/*.g.dart"

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    avoid_catches_without_on_clauses: false
    document_ignores: false
