name: Test

concurrency:
  group: ${{ github.ref }}-test
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - name: Run tests
        run: flutter test --branch-coverage -r github
      # - name: Generate coverage report
      #   run: genhtml coverage/lcov.info -o coverage > coverage/summary.txt
      # - name: Check coverage level
      #   run: dart run scripts/coverage.dart
      - name: Setup LCOV
        run: |
          sudo apt-get -y install lcov
          lcov --version
      # - name: Report code coverage
      #   uses: zgosalvez/github-actions-report-lcov@v3
      #   with:
      #     coverage-files: coverage/lcov.info
      #     minimum-coverage: 99.4
      #     artifact-name: code-coverage-report
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     update-comment: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
